"""v2 end-to-end: parse → extract → load on StructEdgesFixture, asserting the
4 relationship edge types.

Skipped by default (needs Lean build + Neo4j). Enable:
  export LEANATLAS_NEO4J_USER=neo4j LEANATLAS_NEO4J_PASSWORD=... LEANATLAS_NEO4J_DB=neo4j
  export LEANATLAS_RUN_V2_ACCEPTANCE=1
  pytest tests/test_v2_acceptance.py -v -s
"""
import os
import subprocess
from pathlib import Path

import pytest
from neo4j import GraphDatabase

from leanatlas.config import get_config
from leanatlas.models import module_to_json
from leanatlas.parse_source import parse_file

pytestmark = pytest.mark.skipif(
    os.environ.get("LEANATLAS_RUN_V2_ACCEPTANCE") != "1"
    or not os.environ.get("LEANATLAS_NEO4J_PASSWORD"),
    reason="requires LEANATLAS_RUN_V2_ACCEPTANCE=1 and Neo4j credentials",
)

REPO = Path(__file__).resolve().parents[1]
EXTRACT_DIR = REPO / "extract"
FIXTURE = EXTRACT_DIR / "StructEdgesFixture.lean"


def test_v2_four_edges_on_fixture(tmp_path):
    # 1) Build + extract the fixture
    subprocess.run(["lake", "build", "StructEdgesFixture"], cwd=EXTRACT_DIR, check=True,
                   capture_output=True, text=True)
    extract = tmp_path / "e.jsonl"
    with extract.open("w") as f:
        subprocess.run(["lake", "exe", "extract", "StructEdgesFixture"],
                       cwd=EXTRACT_DIR, stdout=f, check=True)

    # 2) Parse the fixture source (Declaration nodes: B/instB/oldB/newB/A/foo)
    rec, warnings = parse_file(str(FIXTURE), root=str(EXTRACT_DIR))
    assert warnings == []
    struct = tmp_path / "s.jsonl"
    struct.write_text(module_to_json(rec) + "\n", encoding="utf-8")

    # 3) Full load (drop first; the single load path carries v2 edges)
    subprocess.run(["python", "-m", "leanatlas.cli", "drop"], cwd=REPO, check=True)
    subprocess.run(
        ["python", "-m", "leanatlas.cli", "load",
         "--structure", str(struct), "--extract", str(extract)],
        cwd=REPO, check=True,
    )

    # 4) Assert the 4 edge types
    cfg = get_config()
    driver = GraphDatabase.driver(cfg.neo4j_uri, auth=(cfg.neo4j_user, cfg.neo4j_password))
    try:
        with driver.session(database=cfg.neo4j_db) as s:
            # EXTENDS: B -> A
            assert s.run(
                "MATCH (:Declaration {name:'StructEdgesFixture.B'})-[:EXTENDS]->"
                "(:Declaration {name:'StructEdgesFixture.A'}) RETURN count(*)"
            ).single()[0] == 1
            # INSTANTIATES: instB -> B
            assert s.run(
                "MATCH (:Declaration {name:'StructEdgesFixture.instB'})-[:INSTANTIATES]->"
                "(:Declaration {name:'StructEdgesFixture.B'}) RETURN count(*)"
            ).single()[0] == 1
            # DEPRECATED_BY (when attrs are readable)
            dep = s.run(
                "MATCH (:Declaration {name:'StructEdgesFixture.oldB'})-[r:DEPRECATED_BY]->"
                "(t:Declaration) RETURN t.name, r.since"
            ).single()
            if dep is not None:
                assert dep[0] == "StructEdgesFixture.newB"
                assert dep[1] == "2024-01-01"
            # HAS_ADDITIVE_VERSION (when attrs are readable; the target addFoo
            # is generated by to_additive and exists only as a placeholder)
            add = s.run(
                "MATCH (:Declaration {name:'StructEdgesFixture.foo'})-[:HAS_ADDITIVE_VERSION]->"
                "(t:Declaration) RETURN t.name"
            ).single()
            if add is not None:
                assert add[0] == "StructEdgesFixture.addFoo"
    finally:
        subprocess.run(["python", "-m", "leanatlas.cli", "drop"], cwd=REPO, check=True)
        driver.close()
